### ISSUE TITLE
Could not load java config file on Github CI

### ISSUE THREAD

**Issue by sdsantos** [hydraulic-software/conveyor#164]
**Describe the bug**
I have a kotlin multi-platform app, and `conveyor make app` runs fine locally. But when running the Github Action I get the following error:

```
Error: Could not load a config file. resource not found on classpath:
stdlib/jdk/21/jetbrains.conf
```

**To Reproduce**
Github CI setup:

```
  desktop-build:
    name: Desktop Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
    
      - name: Run Conveyor (make app)
        uses: hydraulic-software/conveyor/actions/build@v9.1
        with:
          command: make app
          signing_key: placeholder
          agree_to_license: 1
          extra_flags: -Kapp.sign=false
```

**Expected behavior**
The app is built successfully just like locally.

**conveyor.conf**
```
include "#!./gradlew -q composeApp:printConveyorConfig"

// This enables native library extraction, which improves app startup time and robustness.
// It's optional but a good idea to have it. You can remove this if you get tired of specifying
// system properties for Java libraries with native components.
//
// See https://hydraulic.dev/blog/11-in-jar-signing.html for more.
include required("https://raw.githubusercontent.com/hydraulic-software/conveyor/master/configs/jvm/extract-native-libraries.conf")

// Config file documentation: https://conveyor.hydraulic.dev/latest/configs
app {
  vcs-url = "github.com/abc/xyz"

  // This is optional. If not specified the last component of the rdns name will be turned into a display name.
  display-name = "XYZ"

  // A global identifier for the app.
  rdns-name = "com.xyz"

  // For iteration speed. Remove for release.
  compression-level = low

  // Check for and apply updates synchronously on every app launch instead of in the background.
  // updates = aggressive

  mac.info-plist.LSMinimumSystemVersion = "10.15.0"
}

conveyor.compatibility-level = 17
```
